### ISSUE TITLE
toQ14 actually converts to Q15

### ISSUE THREAD

**Issue by wilkinsw** [hcrest/bno080-driver#6]
In the implementation of toQ14 in sh2.c the shift is off by 1 resulting in a Q point of 15.
` int16_t retval = (int16_t)(x * (2<<14));`

The shift should be (1 << 14) so it matches pow(2, 14)
` int16_t retval = (int16_t)(x * (1<<14));`

**Comment by wilkinsw** [comment]
Assuming the number format described here:
https://en.wikipedia.org/wiki/Q_(number_format)#Conversion

**Comment by DaveOfThings** [comment]
Good catch!  Thanks.

**Comment by DaveOfThings** [comment]
After doing a bit of research, I see this bug only affected the sh2_setReorientation() function and internally the sensor hub would re-normalize this quaternion.  So possibly the error would have no effect.  Regardless, I'll push a fix soon.

**Comment by DaveOfThings** [comment]
This has been fixed now, tagged with release v1.1.1.
