### ISSUE TITLE
Redundant if block in opStart()?

### ISSUE THREAD

**Issue by tonypdmtr** [hcrest/bno080-driver#8]
The `if (rc != SH2_OK) {` block (line 1127 in sh2.c) in opStart() seems redundant as the only action is to `sh2.pOp = 0;` which also happens a couple of statements later outside the `if`.  Or, did I miss something?

**Comment by DaveOfThings** [comment]
Looks like a bug to me.  I believe there should be a "return rc;" statement after line 1131, inside the if block.  Without it, the code will hit the sh2_hal_block() call and probably hang forever in this case.

I'll test this change and post an update in a day or two.  But just FYI, this repo, bno080-driver, is deprecated.  The one at github.com/hcrest/sh2 (with corresponding example app at github.com/hcrest/sh2-demo-nucleo) is a similar but redesigned code base that works with the BNO080 and other SH2 sensor hubs.  One of the main design changes is to eliminate these block/unblock calls that were so error prone.

**Comment by tonypdmtr** [comment]
I have already based a lot of code on this driver.  By 'deprecated' you mean it's known to not work correctly in some cases and it should be avoided?

**Comment by DaveOfThings** [comment]
It should work and I'm still maintaining it (working on this issue today, for example.)  If you were starting a new project I'd recommend using the other code base, though.

**Comment by DaveOfThings** [comment]
The fix had been verified and pushed to github now.

**Comment by thealastair** [comment]
We were just about to start forking and fixing this driver to avoid the lockups where sh2_hal_block blocks forever, if this is in fact deprecated it would be great if you could update the readme to indicate this.
